# Build stage
FROM node:22 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Serve stage
FROM nginx:alpine

# Copia build Vue in nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Espone la porta
EXPOSE 80

# Avvia nginx
CMD ["nginx", "-g", "daemon off;"]
