# Usa Node.js 22
FROM node:22

WORKDIR /app

# Copia package.json e installa dipendenze
COPY package*.json ./
RUN npm install

# Copia il resto del frontend
COPY . .

# Build del frontend
RUN npm run build

# Serve con un server statico
RUN npm install -g serve

EXPOSE 80

CMD ["serve", "-s", "dist", "-l", "80"]
