# Usa Python 3.12
FROM python:3.12-slim

WORKDIR /app

# Copia requirements e installa
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia il resto del backend
COPY . .

# Espone la porta
EXPOSE 8000

# Comando per avviare FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
